#!/usr/bin/env ansible-playbook

- name: Configure webserver with nginx
  hosts: servers
  become: true
  tasks:

    - name: rpms
      copy: src=nginx-1.11.0-1.el7.ngx.x86_64.rpm dest=/usr/local/src/

    - name: Install nginx rpm from a local file
      yum:
        name: /usr/local/src/nginx-1.11.0-1.el7.ngx.x86_64.rpm
        state: present

#    - name: copy nginx config file
#      copy: >
#        src=files/nginx.conf
#        dest=/etc/nginx/sites-available/default

#    - name: enable configuration
#      file: >
#        dest=etc/nginx/sites-enabled/default
#        src=etc/nginx/sites-available/default
#        state=link

#    - name: copy index.html
#      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
#        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted

